services:

  postgres:
    image: postgres:15.2
    container_name: template_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
